const sqlite3 = require("sqlite3").verbose()
const path = require("path")
const fs = require("fs/promises")
const packageJson = require("../package.json")
const Converter = require("../library/convertGrammarScopeToDatabaseScope")

const step4 = async () => {
  const currentMajorVersion = parseInt(packageJson.version.match(/^\d+/)[0])
  const versionNumber = currentMajorVersion + 1

  const scopes = await query(`
    SELECT 
      scopes.id AS id,
      scopes.name AS name,
      scope_stacks.content AS original_scope_stack,
      scopes2.name AS cluster_scope_name
    FROM scope_stacks
    INNER JOIN scopes ON scopes.id = scope_stacks.scope_id
    INNER JOIN scopes scopes2 ON scopes.cluster_scope_id = scopes2.id
  `)
  // const scopes = await query(`
  //   SELECT s1.*, s2.name AS cluster_scope_name
  //   FROM scopes s1
  //   INNER JOIN scopes s2 ON s1.cluster_scope_id = s2.id
  // `)

  const primaryScopeNames = []
  const originalScopeStacksByScopeName = {}

  scopes.forEach(({ name, original_scope_stack, cluster_scope_name }) => {
    if (cluster_scope_name !== name) return

    if (!primaryScopeNames.includes(name)) primaryScopeNames.push(name)

    if (!originalScopeStacksByScopeName[name]) {
      originalScopeStacksByScopeName[name] = []
    }

    originalScopeStacksByScopeName[name].push(original_scope_stack)
  })

  let ranksByPrimaryScopeName = Object.fromEntries(
    primaryScopeNames.map(scopeName => [scopeName, 0]),
  )

  let maximumRank = 10

  for (let i = 0; i < maximumRank; i += 1) {
    const scopesByRank = {}
    Object.entries(ranksByPrimaryScopeName).forEach(([scopeName, rank]) => {
      if (!scopesByRank[rank]) {
        scopesByRank[rank] = []
      }
      scopesByRank[rank].push(scopeName)
    })

    const convertGrammarScopeToDatabaseScope = Converter(scopesByRank)

    primaryScopeNames.forEach(scopeName => {
      const originalScopeStacks = originalScopeStacksByScopeName[scopeName]
      if (!originalScopeStacks) return
      for (const originalScopeStack of originalScopeStacks) {
        if (
          originalScopeStack ===
          // "source.css meta.selector.css entity.other.attribute-name.class.css"
          "source.css"
        ) {
          console.log("rank", ranksByPrimaryScopeName[scopeName])
        }
        const matchedScope = convertGrammarScopeToDatabaseScope(originalScopeStack.split(" "))
        if (matchedScope !== scopeName) {
          ranksByPrimaryScopeName[scopeName] += 1
          break
        }
      }
    })

    console.log("Pass", i + 1, "of", maximumRank, "complete")
  }

  const primaryScopeToScopes = {}

  scopes.forEach(scope => {
    if (!primaryScopeToScopes[scope.cluster_scope_name]) {
      primaryScopeToScopes[scope.cluster_scope_name] = []
    }

    if (scope.cluster_scope_name === scope.name) return

    primaryScopeToScopes[scope.cluster_scope_name].push(scope.name)
  })

  const database = { primary: {}, secondary: {} }

  const semanticTokenMappings = {}

  Object.entries(primaryScopeToScopes).forEach(([primaryScopeName, secondaryScopeNames], index) => {
    const color = `color${index + 1}`
    const colorVersion = `color${index + 1}.version${versionNumber}`

    const rank = ranksByPrimaryScopeName[primaryScopeName]

    semanticTokenMappings[colorVersion] = [primaryScopeName]

    database.primary[primaryScopeName] = { semanticToken: color, rank }
    secondaryScopeNames.forEach(secondaryScopeName => {
      database.secondary[secondaryScopeName] = primaryScopeName
    })
  })

  const contributes = {
    configurationDefaults: { "editor.semanticHighlighting.enabled": true },
    semanticTokenScopes: [{ scopes: semanticTokenMappings }],
  }

  const colors = []
  for (let i = 1; i <= Object.keys(primaryScopeToScopes).length; i += 1) {
    colors.push(`color${i}`)
  }

  const capabilities = {
    textDocumentSync: 1,
    semanticTokensProvider: {
      full: true,
      legend: { tokenModifiers: [`version${versionNumber}`], tokenTypes: colors },
    },
  }

  const contributesMd = `<!-- AUTOGENERATED FILE! EDIT IN build-database/step-4-finalize.js -->
# Contributes

Please add the following to the "contributes" section in your extension's package.json:

\`\`\`json
${JSON.stringify(contributes, null, 2)}
\`\`\`
`

  const capabilitiesMd = `<!-- AUTOGENERATED FILE! EDIT IN build-database/step-4-finalize.js -->
# Capabilities

Please add the following to your language server's initialization response. 

If you want, you can 
import the list of colors using:
\`\`\`js
const colors = require('lsp-syntax-highlighter/colors.json')\`
\`\`\`

\`\`\`json
${JSON.stringify(capabilities, null, 2)}
\`\`\`
`

  await fs.writeFile(path.resolve(__dirname, "../database.json"), JSON.stringify(database), {
    encoding: "utf8",
  })

  await fs.writeFile(path.resolve(__dirname, "../contributes.md"), contributesMd, {
    encoding: "utf8",
  })

  await fs.writeFile(path.resolve(__dirname, "../capabilities.md"), capabilitiesMd, {
    encoding: "utf8",
  })

  await fs.writeFile(path.resolve(__dirname, "../colors.json"), JSON.stringify(colors, null, 2), {
    encoding: "utf8",
  })
}

const db = new sqlite3.Database("./data.db", err => {
  if (err) throw err
})

const query = async (sql, parameters = []) => {
  return new Promise(resolve => {
    db.all(sql, parameters, (err, rows) => {
      if (err) throw err
      resolve(rows)
    })
  })
}

step4()
