const sqlite3 = require("sqlite3").verbose()
const path = require("path")
const fs = require("fs/promises")
const initializeGetDatabaseScope = require("../library/getDatabaseScope")

const step4 = async () => {
  const scopes = await query(`
    SELECT *, original_scope_stack AS "originalScopeStack" FROM scopes 
    -- TODO: get rid of these by filtering earlier in the pipeline
    WHERE name != 'default' AND name LIKE '% %'
  `)

  let ranksByScopeName = Object.fromEntries(scopes.map(({ name }) => [name, 0]))

  let maximumRank = 12

  for (let i = 0; i < maximumRank; i += 1) {
    const scopesByRank = {}
    Object.entries(ranksByScopeName).forEach(([scopeName, rank]) => {
      if (!scopesByRank[rank]) {
        scopesByRank[rank] = []
      }
      scopesByRank[rank].push(scopeName)
    })

    const { getDatabaseScope } = initializeGetDatabaseScope(scopesByRank)

    console.log("Pass", i + 1, "of", maximumRank)
    scopes.forEach(({ name: scopeName, originalScopeStack }, index) => {
      if (index % 1000 === 0) console.info("ranking", index, "of", scopes.length)

      if (!originalScopeStack) return

      const matchedScope = getDatabaseScope(originalScopeStack.split(" "))
      if (matchedScope !== scopeName) ranksByScopeName[scopeName] += 1
    })
  }

  const database = {}

  const semanticTokenMappings = {}

  scopes.forEach(({ name: scopeName }, index) => {
    const color = `color${index}`

    const rank = ranksByScopeName[scopeName]

    semanticTokenMappings[color] = [scopeName]

    const firstSpace = scopeName.indexOf(" ")
    const grammarName = scopeName.slice(0, firstSpace)
    const scopeNameRemaining = scopeName.slice(firstSpace + 1)

    if (!database[grammarName]) {
      database[grammarName] = {}
    }

    database[grammarName][scopeNameRemaining] = { semanticToken: color, rank }
  })

  const contributes = `{
    "configurationDefaults": { "editor.semanticHighlighting.enabled": true },
    "semanticTokenScopes": [{ "scopes": 
      ${JSON.stringify(semanticTokenMappings)}
    }],
  }`

  const colors = []
  for (let i = 1; i <= scopes.length; i += 1) {
    colors.push(`color${i}`)
  }

  const capabilities = {
    textDocumentSync: 1,
    semanticTokensProvider: { full: true, legend: { tokenModifiers: [], tokenTypes: colors } },
  }

  const contributesMd = `<!-- AUTOGENERATED FILE! EDIT IN build-database/step-4-finalize.js -->
# Contributes

Please add the following to the "contributes" section in your extension's package.json:

\`\`\`json
${contributes}
\`\`\`
`

  const capabilitiesMd = `<!-- AUTOGENERATED FILE! EDIT IN build-database/step-4-finalize.js -->
# Capabilities

Please add the following to your language server's initialization response. 

If you want, you can 
import the list of colors using:
\`\`\`js
const colors = require('lsp-syntax-highlighter/colors.json')\`
\`\`\`

\`\`\`json
${JSON.stringify(capabilities, null, 2)}
\`\`\`
`

  await fs.writeFile(path.resolve(__dirname, "../database.json"), JSON.stringify(database), {
    encoding: "utf8",
  })

  await fs.writeFile(path.resolve(__dirname, "../contributes.md"), contributesMd, {
    encoding: "utf8",
  })

  await fs.writeFile(path.resolve(__dirname, "../capabilities.md"), capabilitiesMd, {
    encoding: "utf8",
  })

  await fs.writeFile(path.resolve(__dirname, "../colors.json"), JSON.stringify(colors, null, 2), {
    encoding: "utf8",
  })
}

const db = new sqlite3.Database("./data.db", err => {
  if (err) throw err
})

const query = async (sql, parameters = []) => {
  return new Promise(resolve => {
    db.all(sql, parameters, (err, rows) => {
      if (err) throw err
      resolve(rows)
    })
  })
}

step4()
